### PR TITLE
RELATED: WEB-3987 Better version detection

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/65/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Github ref error: SHA of pull request head checked out from remote PR head ref is different from head commit SHA from Github webhook event.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/66/ : SUCCESS in 4s

**Review by Mara3l — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-fossa-scanning-oss-zuul/39/ : SUCCESS in 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-merge-compliance-check/24/ : SUCCESS in 10s

**Pull request merged**
