### PR TITLE
DP-2800 DP-2317 - minor fixes

### PR DESCRIPTION
**Pull request by quanb-duy**
fixed - gap in sidebar navigation, overflow of the docs page, vertical column in tables

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/83/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/84/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/85/ : SUCCESS in 3s

**Review by czechian — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-fossa-scanning-oss-zuul/49/ : SUCCESS in 53s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-merge-compliance-check/34/ : SUCCESS in 7s

**Pull request merged**
