### PR TITLE
WEB-3819   Document Hugo Docs theme

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/36/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/37/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/39/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/40/ : SUCCESS in 4s

**Review by Mara3l — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-fossa-scanning-oss-zuul/25/ : SUCCESS in 1m 17s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-merge-compliance-check/10/ : SUCCESS in 11s

**Pull request merged**
