### PR TITLE
DP-2471 Fix ampersands and nonbreaking spaces in IDs

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/16/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/17/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/18/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/19/ : SUCCESS in 5s

**Review by Mara3l — APPROVED** [review]
lgtm

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-fossa-scanning-oss-zuul/17/ : FAILURE in 4s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-merge-compliance-check/2/ : SUCCESS in 13s

**Pull request merged**
