### PR TITLE
WEB-3837 Hugo theming as a hugo module

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/24/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-oss-check/25/ : SUCCESS in 4s

**Review by Mara3l — APPROVED** [review]
LGTM.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-fossa-scanning-oss-zuul/19/ : SUCCESS in 26s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-docs-theme-merge-compliance-check/4/ : SUCCESS in 9s

**Pull request merged**
